name: unittests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11.0-rc.1"]
        exclude:
          # 1. lxml built-from-source fails or produces unreliable results on these platforms
          # 2. binary wheels are less likely to be available for release candidate versions of Python
          # 3. GitHub Actions cancels all jobs in a batch when a single job fails
          #    ... so skip these platforms
          - os: macos-latest
            python-version: "3.11.0-rc.1"
          - os: windows-latest
            python-version: "3.11.0-rc.1"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # The system-provided libxml2 on MacOS is typically outdated and this can lead to lxml parsing issues
      # Using PyPi-provided binary wheels instead resolves this
      # We are affected by https://bugs.launchpad.net/lxml/+bug/1949271 in test_wild_mode when using system-provided libxml2 on MacOS
      - name: Install lxml from wheel on MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: pip install --only-binary=lxml lxml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Unittest and Coverage Report
        run: |
          python run_tests.py
      # Provide code coverage reports on Linux
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: coveralls.io
        uses: AndreMiras/coveralls-python-action@develop
        with:
          # coveralls repo token
          github-token: "SmlfzlVJy4ow55rduU7IU5GmmFCfAdGeq"
